### ISSUE TITLE
HttpError 501 

### ISSUE THREAD

**Issue by aimartyr** [google-gemini/gemini-api-cookbook#14]
Traceback (most recent call last):
  File "/home/ubuntu/gemini-api-cookbook/preview/file-api/sample.py", line 26, in <module>
    create_file_response = create_file_request.execute()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 501 when requesting https://generativelanguage.googleapis.com/upload/v1beta/files?key=AIzaSyAggwwrhhtetth7tb1dJhfXfuHq_bqM8GQg%0A&alt=json&uploadType=multipart returned "Endpoint not implemented.". Details: "Endpoint not implemented.">
(venv) root@ip-172-3116:/home/ubuntu/gemini-api-cookbook/preview/file-api# python3 sample.py
Traceback (most recent call last):
  File "/home/ubuntu/gemini-api-cookbook/preview/file-api/sample.py", line 26, in <module>
    create_file_response = create_file_request.execute()
  File "/home/ubuntu/venv/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/ubuntu/venv/lib/python3.10/site-packages/googleapiclient/http.py", line 938, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 501 when requesting https://generativelanguage.googleapis.com/upload/v1beta/files?key=AIzhhwhwrhtyAzD7tb1dJhfXfuHq_bqM8GQg%0A&alt=json&uploadType=multipart returned "Endpoint not implemented.". Details: "Endpoint not implemented.">
issue: I have set up a virtual environment on my Ubuntu and followed the steps to run it. I obtained the API and confirmed that I have the permission to use it. However, when I run python3 sample.py, I encountered this issue.Due to security considerations, I obfuscated the API key.

**Comment by TYMichaelChen** [comment]
Hi @aimartyr - thanks for filing the issue. the File API is currently in [private preview](https://github.com/google-gemini/gemini-api-cookbook/blob/main/preview/README.md), so if you see Endpoint not implemented, it is most likely due because File API is not available for your project yet.

**Comment by aimartyr** [comment]
Dear Michael Chen,

Thank you, I removed the file upload module and the code is running successfully now, however sadly it seems I do not have access to 1.5pro, although I had an email to say I would with gemini-1.5-pro-latest, I now have access to geimini-pro. Mine another email address is ***@***.*** which received the API email.

Regards,
Lory.
________________________________
发件人: Michael Chen ***@***.***>
发送时间: 2024年3月28日 11:36
收件人: google-gemini/gemini-api-cookbook ***@***.***>
抄送: miko ***@***.***>; Mention ***@***.***>
主题: Re: [google-gemini/gemini-api-cookbook] HttpError 501 (Issue #14)


Hi @aimartyr<https://github.com/aimartyr> - thanks for filing the issue. the File API is currently in private preview<https://github.com/google-gemini/gemini-api-cookbook/blob/main/preview/README.md>, so if you see Endpoint not implemented, it is most likely due because File API is not available for your project yet.

―
